version: "3.9"  # optional since v1.27.0
services:
  mysql:
    image: mysql:8.0.22
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:5.0.10-alpine3.13
    container_name: myredis